### ISSUE TITLE
No reply to request for fishnet key

### ISSUE THREAD

**Issue by ssb22** [niklasf/fishnet#100]
Hi, this is probably just a documentation bug but I thought I'd better say anyway: when I requested a personal fishnet key, I received no reply.  I assumed that was because my desktop CPU was under 2 GHz, so I applied again using a laptop CPU (2.5GHz) but still received no reply.  I have checked all spam folders etc.  I could not find anything on https://lichess.org/get-fishnet to explain what "no reply" means (something wrong with my application?  fishnet no longer needs new participants?  technical problem with the form?) so I'm raising this as a bug for now; please refile appropriately.  Thanks.

**Comment by ornicar** [comment]
The form works fine, and we pick applicants ourselves.
