### ISSUE TITLE
Improve efficiency by using official Stockfish for standard chess

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#105]

**Comment by bftjoe** [comment]
Anyone working on this? I want to have a shot at implementing this.

**Comment by bftjoe** [comment]
I have this mostly working, will probably submit pull request in a couple of days

**Comment by bftjoe** [comment]
Preliminary support here: 
https://github.com/bftjoe/fishnet/tree/use-stock-stockfish

Apparently we could get another 5% boost on variants if we break out support for antichess? I don't know if it's worthwhile or not.
https://github.com/ddugovic/Stockfish/issues/579

**Comment by niklasf** [comment]
Cool. Regarding splitting more variants, I don't think it's worth it. They are analysed rarely and it would mean opening more processes with permanently reserved hash tables.

**Comment by druyang** [comment]
@bftjoe are you by chance still working on implementing official stockfish? was this merged in?

**Comment by bftjoe** [comment]
I didn't make a pull request yet. I have it working locally.

I am working on a version with different executables for all variants, instead of just 1 variant and 1 standard stockfish. It will switch out the variant stockfish so that not too much memory is used for hash tables.

**Comment by niklasf** [comment]
I don't think separate Stockfish builds for all the variants are worth the slight increase in code complexity, CI builds for precompiled Stockfish, and downloads. Variant games account for ~2%, so even substantial performance improvements will be negligible in the grand scheme of things.
