### ISSUE TITLE
Document update/upgrade steps to track new versions

### ISSUE THREAD

**Issue by paulharris** [niklasf/fishnet#107]
I've custom-built my stockfish binary
but this documentation doesn't mention how I will know if I need to update my fishnet binary when new commits come through on this repo.

There is an --auto-update flag in the python-fishnet commandline,
but what exactly does that autoupdate?  The pip stuff, but not the custom built binary, right?
Does it only auto update when the program is restarted?
ie the server has to be rebooted to see new updates?

What maintenance is required, or is this a set-and-forget kind of server?

Thanks!

**Comment by niklasf** [comment]
`--auto-update` updates at startup, but also checks pypi at random intervals. If new updates are available they will be installed and fishnet will be restarted. This includes precompiled Stockfish updates.

However this does not override `--stockfish-command`. Is there a change you made that should be included in the official build?

**Comment by paulharris** [comment]
I didn't make a change, but I do know that you can ask the compiler to compile with ALL of the CPU support enabled with -march=native

Would be good if you could allow it to auto-compile stockfish with all of the performance flags on for the particular platform.

In the meantime, I'll switch back to auto-downloaded releases.

**Comment by niklasf** [comment]
Relevant CPU features are all ready [detected](https://github.com/niklasf/fishnet/blob/6d08ea0e3ebeb7c9c5bb2530f826f7282f9ae3cc/fishnet.py#L980) and considered when chosing the binary to download.
