### ISSUE TITLE
[RPi] Problem with stockfish update

### ISSUE THREAD

**Issue by mayweed** [niklasf/fishnet#108]
Lo
I want to run fishnet on an old Pi2. I installed Raspbian Buster, built stockfish (with [some compile glitches](https://github.com/official-stockfish/Stockfish/issues/2641) ) but in the end i was able to install it.

I installed fishnet with pip3 and ran it with:
`python3 -m fishnet --auto-update --stockfish-command /usr/local/bin/stockfish`

But nonetheless it was not possible to run it because you dont provide arm binaries (i might help with that by the way, so if you need some help to get builds let me know eventually)
and the update was of course not possible 
```
ERROR: Configuration error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/fishnet.py", line 2075, in main
    sys.exit(commands[args.command](args))
  File "/home/pi/.local/lib/python3.7/site-packages/fishnet.py", line 1638, in cmd_run
    stockfish_command = get_stockfish_command(conf)
  File "/home/pi/.local/lib/python3.7/site-packages/fishnet.py", line 1576, in get_stockfish_command
    filename = update_stockfish(conf, filename)
  File "/home/pi/.local/lib/python3.7/site-packages/fishnet.py", line 1116, in update_stockfish
    return download_github_release(conf, STOCKFISH_RELEASES, filename)
  File "/home/pi/.local/lib/python3.7/site-packages/fishnet.py", line 1086, in download_github_release
    raise ConfigError("No precompiled %s for your platform" % filename)
ConfigError: No precompiled stockfish-armv7l for your platform
```
My question is: is there a way to disable that update ? I first thought that's what --stockfish-command option was for...
Thx for your help

**Comment by niklasf** [comment]
Hi, thanks for reporting.

Regarding `--stockfish-command`, it should work. Was it maybe overwritten by the configuration dialog? Going to fix that. If not, could you please share the entire log of the session with `-vvv`.

https://github.com/niklasf/Stockfish fork of multi-variant Stockfish that we use. The binaries are created by `.travis.yml` (Linux, OS X) and `appveyor.yml` (Windows). I am happy to consider other platforms for arm support. Maybe GitHub actions?

**Comment by niklasf** [comment]
Potential fix for ignored command line flags published in `v1.17.2`.

**Comment by mayweed** [comment]
Hi @niklasf 
I lauch fishnet this morning via ssh on my Pi and with the new update it works fine. Chances are, i will be able to devote this oldie to lichess ai :)

Could you be please more about how to build a binary that could be inserted into your project?  I never worked with travis before neither with GH actions. So as a starting point could you please give me the travis.yml file you use to build your current binaries?

Thx for everything :)

**Comment by niklasf** [comment]
Yay :)

Here are some relevant files:
https://github.com/niklasf/Stockfish/blob/fishnet/.travis.yml
https://github.com/niklasf/Stockfish/blob/fishnet/linux_build.sh
https://github.com/niklasf/Stockfish/blob/fishnet/appveyor.yml
https://github.com/niklasf/Stockfish/blob/fishnet/msys_build.sh

**Comment by mayweed** [comment]
Thx will look at that!!  Just a last question: is there any way to test those builds via travis in a replica environnement? I do need to be able to test before propose... :)

**Comment by niklasf** [comment]
You could fork that repository, log into Travis with your GitHub account and enable it for your repository. Or test the script locally, and hope that it works similarly in CI.
