### ISSUE TITLE
Update to Stockfish 12

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#119]
* [ ] Maybe #105
* [ ] Set `Use NNUE`, and only where supported
* [ ] Detect support for vector instructions. ~Do not use NNUE where it would be slower?~
* [ ] Node limits with and without NNUE are not equivalent in time and strength
* [x] Build binaries for different CPUs (https://github.com/niklasf/fishnet-assets)

**Comment by ProteinGolem** [comment]
Do you think the 3rd one is hardest?

**Comment by druyang** [comment]
@niklasf would love to help contribute, was #105 done with [bftjoe's branch](https://github.com/bftjoe/fishnet/tree/use-stock-stockfish)?
