### ISSUE TITLE
Does fishnet work on the Raspberry Pi 4?

### ISSUE THREAD

**Issue by fncll** [niklasf/fishnet#122]
Does fishnet run on the Raspberry Pi 4? I saw one issue here that implied it might but there were issues with the stockfish needed? And would the Raspberry Pi be powerful enough to make a meaningful contribution?

**Comment by niklasf** [comment]
It should work by using the `build-stockfish.sh` script from this repository and then using `python -m fishnet --stockfish-command ./stockfish-armv7`. But I don't expect great performance. It's probably better to let people with servers or actively cooled desktops contribute.

**Comment by pmatuszy** [comment]
indeed your hint helps:

you need to run:
pip install fishnet


then 
python -m fishnet --stockfish-command ./stockfish-armv7

but I get this log:

`.   _________         .    .
.  (..       \_    ,  |\  /|
.   \       O  \  /|  \ \/ /
.    \______    \/ |   \  /      _____ _     _     _   _      _
.       vvvv\    \ |   /  |     |  ___(_)___| |__ | \ | | ___| |_
.       \^^^^  ==   \_/   |     | |_  | / __| '_ \|  \| |/ _ \ __|
.        `\_   ===    \.  |     |  _| | \__ \ | | | |\  |  __/ |_
.        / /\_   \ /      |     |_|   |_|___/_| |_|_| \_|\___|\__| 1.18.2
.        |/   \_  \|      /
.               \________/      Distributed Stockfish analysis for lichess.org


### Configuration

Engine working directory (default: /root/fishnet/fishnet-2.4.0):

Fishnet uses a custom Stockfish build with variant support.
Stockfish is licensed under the GNU General Public License v3.
You can find the source at: https://github.com/ddugovic/Stockfish

You can build lichess.org custom Stockfish yourself and provide
the path or automatically download a precompiled binary.

ENGINE: 31729 << uci
ENGINE: 31729 >> Stockfish 280921 by the Stockfish developers (see AUTHORS file)
ENGINE: 31729 >> id name Stockfish 280921
ENGINE: 31729 >> id author the Stockfish developers (see AUTHORS file)
ENGINE: 31729 >>
ENGINE: 31729 >> option name Debug Log File type string default
ENGINE: 31729 >> option name Threads type spin default 1 min 1 max 512
ENGINE: 31729 >> option name Hash type spin default 16 min 1 max 2048
ENGINE: 31729 >> option name Clear Hash type button
ENGINE: 31729 >> option name Ponder type check default false
ENGINE: 31729 >> option name MultiPV type spin default 1 min 1 max 500
ENGINE: 31729 >> option name Skill Level type spin default 20 min 0 max 20
ENGINE: 31729 >> option name Move Overhead type spin default 10 min 0 max 5000
ENGINE: 31729 >> option name Slow Mover type spin default 100 min 10 max 1000
ENGINE: 31729 >> option name nodestime type spin default 0 min 0 max 10000
ENGINE: 31729 >> option name UCI_Chess960 type check default false
ENGINE: 31729 >> option name UCI_AnalyseMode type check default false
ENGINE: 31729 >> option name UCI_LimitStrength type check default false
ENGINE: 31729 >> option name UCI_Elo type spin default 1350 min 1350 max 2850
ENGINE: 31729 >> option name UCI_ShowWDL type check default false
ENGINE: 31729 >> option name SyzygyPath type string default <empty>
ENGINE: 31729 >> option name SyzygyProbeDepth type spin default 1 min 1 max 100
ENGINE: 31729 >> option name Syzygy50MoveRule type check default true
ENGINE: 31729 >> option name SyzygyProbeLimit type spin default 7 min 0 max 7
ENGINE: 31729 >> option name Use NNUE type check default true
ENGINE: 31729 >> option name EvalFile type string default nn-13406b1dcbe0.nnue
ENGINE: 31729 >> uciok
DEBUG: Supported variants:
ERROR: Configuration error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fishnet.py", line 2379, in main
    sys.exit(commands[args.command](args))
  File "/usr/local/lib/python3.7/dist-packages/fishnet.py", line 1940, in cmd_run
    conf = load_conf(args)
  File "/usr/local/lib/python3.7/dist-packages/fishnet.py", line 1354, in load_conf
    conf = configure(args)
  File "/usr/local/lib/python3.7/dist-packages/fishnet.py", line 1461, in configure
    stockfish_command = validate_stockfish_command(args.stockfish_command, conf)
  File "/usr/local/lib/python3.7/dist-packages/fishnet.py", line 1575, in validate_stockfish_command
    "Unsupported variants: %s" % ", ".join(missing_variants))
ConfigError: Ensure you are using lichess custom Stockfish. Unsupported variants: kingofthehill, giveaway, atomic, racingkings, chess, horde, 3check, crazyhouse
`
