### ISSUE TITLE
Remove dependency on glibc for Linux builds of Stockfish

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#129]
Statically linking musl is easy for the Rust client, but so far I have failed to create statically linked Stockfish builds.

The current build script is https://github.com/niklasf/Stockfish/blob/fishnet-master/.github/workflows/build.yml

**Comment by teotwaki** [comment]
@niklasf You might want to do some performance testing prior to committing to musl. Although I'm a big fan of it and run it on my daily driver, there are reports that musl induces some serious poor performance for multithreaded code. Some theories appear to point at the allocator implementation, as jemalloc seems to improve things.

- https://andygrove.io/2020/05/why-musl-extremely-slow/
- https://github.com/BurntSushi/ripgrep/issues/1268
- https://users.rust-lang.org/t/optimizing-rust-binaries-observation-of-musl-versus-glibc-and-jemalloc-versus-system-alloc/8499
