### ISSUE TITLE
Investigate upx

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#131]
https://upx.github.io/ seems to be pretty good at further reducing the binary size. Try adding it to CI and test on various platforms. Could also consider replacing the internal asset compression.

Thanks @teotwaki, for the recommendation.

**Comment by niklasf** [comment]
Bytes without removing internal compression (on x86-64 linux):

```
cargo build --release 26708576
strip                 20090392
upx                   15764148
upx --best            16270792 # sic
upx --brute           13824852
```

**Comment by niklasf** [comment]
Looks like the `upx --brute` binary is broken, though. Cba to deal with this entirely new class of possible bugs.

**Comment by teotwaki** [comment]
I'm fairly experienced with using UPX. I'll provide a PR soon.

**Comment by teotwaki** [comment]
```
cargo build --release    26752512 (works) 0.00s
strip                    20147752 (works) 0.00s
upx                      15723916 (works) 0.06s
upx --best               16247304 (works) 0.04s
upx --lzma               13719864 (works) 0.72s
upx --best --lzma        13717968 (works) 0.72s
upx --brute              13807624 (breaks) n/a
```

A few things worthy of note:

- Using LZMA significantly increases the start up time of the process, going from virtually instant to needing the better part of a second to start.
- UPX 3.96 doesn't work on modern Rust for me. I had to use the `devel` branch of UPX to get it to accept the DT_GNU_HASH that Rust produces. More info [here](https://github.com/upx/upx/issues/369).
- The UPX maintainer/author indicates that `--lzma` is equivalent to `--brute` for very large binaries. See [here](https://github.com/upx/upx/issues/224#issuecomment-425316668).

@niklasf I'll let you decide whether it's worth pursuing.

**Comment by niklasf** [comment]
Eh, let's keep it simple. It's substantial improvement, but not very important, in the grand scheme of things.
