### ISSUE TITLE
systemd log shows some jobs without complete url and they dont resolve to games on lichess

### ISSUE THREAD

**Issue by jim-perkins** [niklasf/fishnet#134]
not sure if these are some type of error, aborted jobs or what.  usually the completed jobs look like this:

Nov 30 11:21:38 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [=====|======     ] https://lichess.org/A8gPz5AS finished (6960 knps)

however I have some jobs that are missing 'https://lichess.org/'.   If I try to manually create the url the lichess website gives a 404.

journalctl -u fishnet2.service | grep finished | grep -v https 

... snipped for brevity
Nov 30 06:52:12 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [     |           ] 8iR9FEoF finished (8902 knps)
Nov 30 07:39:57 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [=====|=======    ] qSTybmpE finished (8935 knps)
Nov 30 08:50:52 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [=====|====       ] 9wVHLthS finished (3297 knps)
Nov 30 09:10:26 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [=====|=====      ] amFVIPKx finished (6176 knps)
Nov 30 10:00:21 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [=====|=          ] vlijhFMj finished (8856 knps)
Nov 30 10:41:06 lichess fishnet-x86_64-unknown-linux-gnu[1104]: [=====|===========] rncUfpCq finished (7991 knps)

journalctl -u fishnet2.service | grep finished | grep -v https | wc -l
29

**Comment by niklasf** [comment]
Thanks for taking the time to report issues like this!

This one is intended. There are currently unlisted studies (and in the future maybe other batch types), where we don't want to leak the URL. Studies could contain private commentary, for example.

**Comment by jim-perkins** [comment]
thanks .  I do now see that this behavior was present in fishnet 1.x  .  of the ~712k games my machine analyzed with fishnet 1.x, appx .5% were opaque batch ids.  Currently running about .3% on my very small batch of fishnet 2.x .  Thanks for taking the time to explain this to me.  I'll keep poking around :-)
