### ISSUE TITLE
Allow fishnet volunteers to view unencrypted data via SSLKEYLOG environment setting

### ISSUE THREAD

**Issue by jim-perkins** [niklasf/fishnet#138]
Would you consider a PR to allow fishnet to honor the SSLKEYLOG[(1)](https://wiki.wireshark.org/TLS#TLS_Decryption) environment variable so that wireshark could view the unencrypted data that fishnet sends back to lichess.org ?   

I am willing to take a hack at an acceptable PR.  Currently reqwest does not directly support SSLKEYLOG. [(2)](https://github.com/seanmonstar/reqwest/pull/1057#issuecomment-708668848).  The work around is to injecting a custom rustls config into the client. [(3)](https://github.com/seanmonstar/reqwest/issues/1016#issue-684250453).  However this may be beyond my skill level and if you considered adding this to fishnet a worthwhile expense of your time and effort I would be appreciative.

As an interim solution I have forked reqwest[(4)](https://github.com/jim-perkins/reqwest/commit/cdb823aa53ce0904964629b4bf45c3e72c09cbb3) and fishnet [(5)](https://github.com/jim-perkins/fishnet/commit/a2ce82bbf488db6a3535366125757ab5f08038d4) and compiled a working version of fishnet that supports SSLKEYLOG .  This of course isn't acceptable for a PR.  However I was able to view the unencrypted data which satisfied my curiosity . 

## Rationale ##

* Fishnet volunteers should have the ability to view the data that their machines is generating.
  * security
  * curiosity
  * debug
  * development
  * other
* Fishnet 2.x is a compiled program and the end user cannot easily add this feature.
  *  with fishnet 1.x it was easy to modify the python code to support SSLKEYLOG. [(6)](https://github.com/jim-perkins/fishnet/blob/ssl_key/fishnet.py#L56)
* Fishnet currently doesn't support, or I was unable to produce, reproducible builds. [(7)](https://github.com/niklasf/fishnet/issues/128)
* This change has limited security concerns
  * I admit my knowledge on this area is very limited
  * It is understandable to use https for fishnet as 'Lets Encrypt' makes it simple to move your whole site to https. The entire Internet is moving to 'HTTPS everywhere'.
  *  The only thing transmitted which is confidential is the 'fishnet key'
  * If the attacker can set an environmental string affecting fishnet then they can access the fishnet key thru fishnet.ini
  * If the environmental string is not set then the code does not publicize the keys.

Thanks for your consideration and all the work on fishnet.  I really like the new version as it better utilizes all the cores available and processes the analysis quicker.

**Comment by bftjoe** [comment]
It might be easier to make a fishnet "client" that forwards the requests to your own fishnet server and then view unencrypted http communications between server-client unencrypted.

**Comment by jim-perkins** [comment]
Thanks for the reply.  You may be right as my initial attempt using the example code listed above within fishnet did not work.  Plan on giving it another go and asking for help in a rust forum in the future. 

While not specifically what you mentioned, posing as the 'man in the middle' just feels fundamentally wrong when 'I AM the man'.  Realize I am not very knowledgeable on standard practices regarding viewing your own https traffic.

But in the meantime my forked version works.  If anyone else has the desire to view the http conversation they could utilize that.  If they need help I would be glad to assist.

**Comment by jim-perkins** [comment]
Niklas, thanks so much.  I am very grateful for you making the PR.  I was close with my attempt but a few lines off.  Not sure of proper etiquette but went ahead and removed my forks from github as they are no longer needed and edited earlier comments to reflect that.  I owe you one :-)  I'll try to keep an eye out on the 'help wanted' tag to see if there is anything I can do.  Thanks again.
