### ISSUE TITLE
Mistakes in stockfish analysis

### ISSUE THREAD

**Issue by lazydroid** [niklasf/fishnet#143]
I'm not sure this is the right place, but I could not find the correct one to ask.

In the following game the move 14. Bg5 changes evaluation (in my browser, depth 22) from +1.0 to -0.4, though this is not marked as "Mistake" or "Inaccuracy" : https://lichess.org/UaA5ftj2#26

Is this a bug and what could I do about that?

**Comment by niklasf** [comment]
The inaccuracies/mistakes/blunders are based on server-side analysis. At that depth, the change is from +0.46 (displayed as +0.5) to 0.

According to Lichess's winning chance model, the expectation value for winning the game went from 0.546 to 0.5, which is a difference just below the 0.05 threshold for what Lichess calls an inaccuracy.
