### ISSUE TITLE
Don't use NNUE in variants

### ISSUE THREAD

**Issue by benwh1** [niklasf/fishnet#147]
Using a network trained on classical chess to analyse variant games doesn't make any sense. In particular, the atomic analysis on lichess is much worse than it was before the update (I haven't tested the other variants). For example see [this position](https://lichess.org/Z9aJ0uOH/white#51). The analysis says the position is slightly better for black, but it's actually completely winning for white. Running the latest stockfish on my computer, it immediately says +3 for white with NNUE disabled, but takes 10 seconds to go above 0 with NNUE enabled.

**Comment by bharrisau** [comment]
Variants are handled by a Stockfish branch AFAIK. ddugovic/Stockfish#158 is looking for good benchmarking examples to make sure there aren't any performance regressions - this is probably a good example.

**Comment by niklasf** [comment]
Oh, wow, I was (apparently incorrectly) assuming multi-variant Stockfish would not use NNUE for variants.

**Comment by niklasf** [comment]
Released in v2.1.3.
