### ISSUE TITLE
os error 10054 with x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#154]
https://lichess.org/forum/lichess-feedback/error-when-fishnet-start

```
><> Checking for updates (--auto-update) ...
Checking target-arch... x86_64-pc-windows-gnu
Checking current version... v2.2.0
Checking latest released version... v2.2.0
><> Fishnet 2.2.0 is up to date

### Checking configuration ...

Endpoint: lichess.org/fishnet
Backlog: Join queue if user backlog >= 30s or system backlog >= 3600s
CPU features: POPCNT | SSE | SSE2 | SSSE3 | SSE41 | AVX2 | BMI2 | SF_SSE2 | SF_SSSE3 | SF_SSE41_POPCNT | SF_AVX2
Engine: stockfish-x86-64-avx2.exe (for GPLv3, run: fishnet-x86_64-pc-windows-gnu.exe license)
Cores: 15

### Running (CTRL-C to stop) ...

E: error sending request for url (lichess.org/fishnet/status): error trying to connect: Se ha forzado la interrupción de una conexión existente por el host remoto. (os error 10054). Backing off 384ms.
E: error sending request for url (lichess.org/fishnet/status): error trying to connect: Se ha forzado la interrupción de una conexión existente por el host remoto. (os error 10054). Backing off 234ms.
E: error sending request for url (lichess.org/fishnet/acquire?slow=false): error trying to connect: Se ha forzado la interrupción de una conexión existente por el host remoto. (os error 10054). Backing off 121ms.
```

**Comment by niklasf** [comment]
Related: https://support.microsoft.com/en-us/help/981344/an-application-may-receive-the-10054-error-when-the-application-receiv

**Comment by JSCjr** [comment]
Have been seeing sporadic messages like this with aarch64-macos as well. Had assumed that it was a network/connection hiccup vice a bug.

    [=====|===========> https://lichess.org/4vxnEm8q finished (10219 knps)
    [     |           ] 7 cores, 0 queued, latest: https://lichess.org/4rexljAH#11 
    [     |           ] https://lichess.org/4rexljAH finished (8232 knps)
    E: error sending request for url (https://lichess.org/fishnet/acquire?slow=false): connection error: broken pipe. Backing off 289ms.
    E: error sending request for url (https://lichess.org/fishnet/acquire?slow=false): connection error: broken pipe. Backing off 303ms.

**Comment by niklasf** [comment]
Yes, those appear to be "normal" hickups. The reported `os error 10054` is very specific, and happening quite reliably and very frequently.

**Comment by niklasf** [comment]
Confirmed not to be toolchain specific:
> In version 2.1.3 it also happens.
That version was still built with MSVC.

**Comment by niklasf** [comment]
Seems to be mysteriously solved, now. Let's close it until someone else also has this issue.
