### ISSUE TITLE
Prepared changes lists wrong key for multipv/depth

### ISSUE THREAD

**Issue by lakinwecker** [niklasf/fishnet#158]
https://github.com/niklasf/fishnet/blob/master/src/api.rs#L124-L127
https://github.com/niklasf/fishnet/blob/master/doc/protocol.md#prepared-changes

In the protocol.md doc, it lists `work.analysis.multipv` and `work.analysis.depth` but the actual code puts it directly in `work.multipv` and `work.depth`

Or maybe I'm reading that code wrong and maybe the entire thing goes in `work.analysis` including `nodes` and the thing that is wrong is the `Response with work:` from the doc?

**Comment by niklasf** [comment]
Oops. Confused the internal enum variant `Work::Analysis` with how it looks in JSON. Makes more sense to put these right next to `nodes`.
