### ISSUE TITLE
Occasional engine errors

### ISSUE THREAD

**Issue by JonathanBrouwer** [niklasf/fishnet#160]
I am every so often getting the following error:
```
[=====|=          ] 7 cores, 8 queued, latest: https://lichess.org/igg8JtJs#23 
E: Engine error: unexpected end of file
W: Worker 4 waiting for engine to shut down after error. Context: https://lichess.org/igg8JtJs#24
W: Aborting batch FCRIeuUA.

```
Sometimes I can go a few hours without having this error, other times I have multiple in one minute.
Any idea what could cause this?

System information:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700K CPU @ 4.00GHz
Memory: 15,6 GiB of RAM
Graphics Processor: GeForce GTX 970/PCIe/SSE2
```

**Comment by niklasf** [comment]
Just to confirm, which `fishnet --version` is this?

**Comment by JonathanBrouwer** [comment]
`fishnet 2.2.0`

**Comment by jim-perkins** [comment]
grepped the journalctl of my 2 instances of fishnet and could not find any  'Engine error'.  System has older processors so fishnet is using stockfish-x86-64-sse41-popcnt , if that makes a difference. hth

**Comment by niklasf** [comment]
Alright, thanks. I can't reproduce the issue locally on the same game, even though Stockfish analysis is supposed to be deterministic.

Let's exclude that it's due to the order of distributing positions to processes. Can you please run your instance with `--cores 1` for a while, and paste any errors here, if they still happen?

**Comment by JonathanBrouwer** [comment]
Hm I just got another error which I haven't seen before
```
[===  |           ] 7 cores, 5 queued, latest: https://lichess.org/vjaAlkWd#15*** stack smashing detected ***: terminated
```
I've had some issues with my cpu before, so I think this might actually be hardware problems. (Especially considering you can't reproduce this)
I'll try running a few stress tests and seeing if I can get them to fail

**Comment by JonathanBrouwer** [comment]
These were indeed most likely hardware errors. Sorry for bothering you!
