### ISSUE TITLE
How to enable feature 'bool_to_option' when compling on Windows 10?

### ISSUE THREAD

**Issue by chn-cutelotus** [niklasf/fishnet#175]
Checking shakmaty v0.18.0
error[E0658]: use of unstable library feature 'bool_to_option'                                                             
   --> C:\Users\Lotus\.cargo\registry\src\crates.rustcc.com-a21e0f92747beca3\shakmaty-0.18.0\src\fen.rs:459:110
    |
459 |         } else if let Some(split_point) = board_part.iter().enumerate().filter_map(|(idx, ch)| (*ch == b'/').then(|| 
idx)).nth(7) {
    |                                                                                                              ^^^^    
    |
    = note: see issue #64260 <https://github.com/rust-lang/rust/issues/64260> for more information
    = help: add `#![feature(bool_to_option)]` to the crate attributes to enable

error: aborting due to previous error                                                                                      

For more information about this error, try `rustc --explain E0658`.
error: could not compile `shakmaty`.

To learn more, run the command again with --verbose.

**Comment by niklasf** [comment]
Hi. This requires Rust 1.50. If you have installed Rust using rustup, simply `rustup update` to update to the latest stable.
