### ISSUE TITLE
Inconsistent game analysis

### ISSUE THREAD

**Issue by zachee54** [niklasf/fishnet#181]
Hello,
I realized that some of my games came into an inconsistent analysis.
Last example : https://lichess.org/xFkEBRTF
The end of game is analysed as follows :
![image](https://user-images.githubusercontent.com/42939319/113744578-1f424700-9705-11eb-9a9b-0d7869158cfe.png)
Logically, if white can mate in 12 after playing 26.Kf6+, they could also mate in 13 after the previous black move 25.Rf7. Actually, the evaluation must also be #12 after the next black move 26...Qxf6, and not +24.4 as displayed.
This doesn't make sense.

This is not the first time I notice such inconsistencies, but at first I passed through. I can remember that after my opponent moved I could mate in n moves, and when I moved the game was then evaluated to #(n-3) instead of, at least, #(n-1).

For information, all my games analysis were requested from the mobile app.
Hope it will help.

**Comment by niklasf** [comment]
Thanks for reporting.

Unfortunately, this is by design. The positions are analysed independently and engines use various heuristics to prune the search tree. A mate is guaranteed to actually be a mate, but other scores are not guaranteed not to be mate when searching deeper.
