### ISSUE TITLE
GitHub Actions: macos-aarch64 build fails

### ISSUE THREAD

**Issue by gbedoya** [niklasf/fishnet#189]
GitHub Actions build for MacOS Big Sur fails ...
```No runner matching the specified labels was found: macos-11.0```

Build error observed here ...
https://github.com/gbedoya/fishnet/actions/runs/923004435

Per documentation[1] of GitHub Actions virtual environments ...

Virtual environment | YAML workflow label
-- | --
macOS Big Sur 11 | macos-11 

_Note: The macOS 11 virtual environment is currently provided as a private preview only._

In other words, changing the target to correct `macos-11` won't fix this issue as Big Sur virtual environment is private preview only.

Should Big Sur build be removed? Moved to another branch? Or ...

[1] https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by niklasf** [comment]
All repositories that were using it prior to that decision were grandfathered in. So it's working in this repository, but not in your fork.

**Comment by niklasf** [comment]
Looks like this applies also to pull request builds, so feel free to make pull requests to test stuff, if you like.
