### ISSUE TITLE
Throttle acceptance of jobs

### ISSUE THREAD

**Issue by Syoc** [niklasf/fishnet#194]
Hi,
I wanted to contribute to Lichess by running fishnet on a home server.
This proved to generate too much heat and noise as all cores were continuously pegged.
Now if there was some throttle on the amount of work requests accepted by fishnet I could probably find a value that works for me.
I assume that would be better than resource limiting the jobs as that would lead to slower analysis for the users.

**Comment by jim-perkins** [comment]
Hi.  Either of these commands will show me how to adjust the amount of cores that fishnet uses.  Your exact executable is probably different .

fishnet-x86_64-unknown-linux-gnu -help
fishnet-x86_64-unknown-linux-gnu configure

**Comment by greatericontop** [comment]
Do you mean an option like `--reduce-threads-by-one-when-junction-temperature-exceeds=...`, or just limiting how many games you analyse?

**Comment by Syoc** [comment]
I was thinking something along the lines of `--accept-X-analyses-per-hour=X`.
It would be hard to define heuristics that would work for everyone. Some might be bothered by temperature, power usage, noise etc. Having users approximate their needs with a more general "do X jobs per Y" approach is probably easier.

There are multiple ways of having fishnet use a given amount of cores and even throttling the usage of those cores, even if fishnet had no options for it. I just thought it would be better for there to be fewer but faster analyses than continuous slow ones.

**Comment by Syoc** [comment]
Well I found the excellent backlog options now and they will do just fine for my purposes.
I used the docker container earlier and was thus not exposed to the nice config helper.
I'll just close this issue even if it's not a perfect match. Thank you for the suggestions.
