### ISSUE TITLE
Heroku fishnet

### ISSUE THREAD

**Issue by Aromik** [niklasf/fishnet#198]
Hello! Trying to deploy the fishnet to heroku. Everything is good, but it's saying that the prompts are coming from the wrong port (not 5000) and it doesn't work. I use the binary, which I simply upload to heroku and run. It works, but then it says, that "Web process failed to bind to $PORT within 60 seconds of launch"/ How to fix it? Thanks

**Comment by Osrepnay** [comment]
Heroku doesn't allow you to open any arbitrary port, only the value in the PORT environment variable, which binds to the http port 80 (?) if I remember correctly

**Comment by niklasf** [comment]
fishnet does not require any open inbound ports, but if I understand correctly, Heroku is intended to provide services via HTTP, not to execute long running computations like fishnet. The fishnet client itself is not an HTTP server. So I think it just does not fit that platform.
