### ISSUE TITLE
Fishnet remains idle

### ISSUE THREAD

**Issue by hellownaman** [niklasf/fishnet#219]
My fishnet remains idle 50 % of the time .. without analysing any games even if there are around 35+ games available in the system queue as per the status webpage of fishnet.

Is this intentional or some kind of bug?

Note - the average speed of my processor is about 1800 knps

**Comment by niklasf** [comment]
Hi, thanks for running fishnet!

fishnet tries to estimate when your client would complete an analysis, compared to when a faster client would complete the analysis, including wait time for a faster client to become available. 1800 knps is relatively low, so it's expected that it often waits for faster clients.
