### ISSUE TITLE
doesn't run when IPv6 is disabled

### ISSUE THREAD

**Issue by darkBuddha** [niklasf/fishnet#245]
`E: error sending request for url (https://lichess.org/fishnet/key): error trying to connect: dns error: Address family not supported by protocol (os error 97). Backing off 255ms.`

**Comment by niklasf** [comment]
Thanks for looking into it!

**Comment by niklasf** [comment]
Mhh ... I don't think so. That's just intended to mean that lichess.org can be reached via IPv6.
