### ISSUE TITLE
adaptive movetime on play move

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#27]
only use the nps when level=8 (and when there is no score.mate) to continuously adapt the movetime value.

**Comment by niklasf** [comment]
4426c6b830b3693db9 to be monitored carefully

**Comment by ornicar** [comment]
Yeah I've seen 2400ms on level 8, a bit crazy. Probably that was not a good idea after all. Single benchmark on start will do better, since move servers use 1 thread per process.
