### ISSUE TITLE
deploy in container

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#3]
deploying the python client is easy. the sript runs without dependencies using python 2 or 3. however we also have to deploy stockfish.

@lukhas i remember you wanted to look into this, at some point

**Comment by ornicar** [comment]
In fact I don't know if we need containers. Might be overkill.

What we need is a very easy way for people to install and run it. We need some magic. Ideally it should install painlessly on at least Linux and OSX (I don't dare asking for the other one). A one-liner that takes care of installing stockfish, no questions asked.

**Comment by niklasf** [comment]
agreed. we probably would only have needed this, if we went the scala route
