### ISSUE TITLE
use nodes instead of movetime to limit analysis

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#37]
```
go nodes 1000000
```

Actually we're limiting on movetime, and adjusting movetime based on nps. It seems like what we really want is ensure a certain number of nodes are crunched for each move, and since version 7 stockfish allows that.

Benefits:

- No need to run initial benchmark!
- No need to adjust movetime!
- Clients can run with a Nice value, it doesn't matter that stockfish gets a full core. If the computer is running something else, the current move will take longer to analyse, but the quality remains the same.

Cons:

- ?

**Comment by niklasf** [comment]
intresting. pinging @ddugovic

we should test some of those crowded positions where movetime wasn't working well in the official stockfish.

**Comment by ornicar** [comment]
Based on monitoring data, I suggest using 2,800,000 nodes for analysis. And a time limit of, say, 1 second * threads, as a guardrail.

**Comment by niklasf** [comment]
and for playing, interpolate the number of nodes the same way we now choose movetime?

**Comment by ornicar** [comment]
not sure about that. playing is less important anyway, since the depth is usually enough to end computing.

**Comment by ddugovic** [comment]
IMHO for playing it's desirable to have some variety in number of nodes searched, similar to how a human player tends to move (more so based on time, less so based on how much the human player actually saw).

@ornicar is probably correct that depth is usually enough to end searches, but I don't know for certain (it might mean AIs spend more time thinking on shallow searches).  On my lila instance for playing I scaled search time linearly with AI level, which seemed to work well and reduce CPU usage, allowing it to play more games at once.

**Comment by niklasf** [comment]
done. using fixed number of nodes for analysis, fixed movetime (~ the one from grafana) for play.
getting rid of the benchmarking and movetime adjustment cruft is feeling good.
