### ISSUE TITLE
--silent option

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#47]
The move nodes can output up to a hundred lines per second to stdout. That's a lot of data with no use.

When ran with `--silent` fishnet would only output the summary message every minute.

I could (and actually do) `> /dev/null` but having the summary every minute would be nice.

**Comment by niklasf** [comment]
```
Default: INFO, PROGRESS information is collapsed
-v: Do not collapse PROGRESS
-vv: DEBUG
-vvv: ENGINE
```
