### ISSUE TITLE
prod move server crash

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#52]
https://gist.github.com/ornicar/e38cd4212cab1e46ab25

it goes on and on.

**Comment by niklasf** [comment]
so only one thread goes crazy? `-vvv` output might be intresting.

also version 1.3.5 now at least uses a backoff for `EOFError`

**Comment by niklasf** [comment]
since the current job is kept when the engine process crashes and is simply restarted, this might be explained by ornicar/lila#1132 or anythingthing else that consistently let's stockfish segfault.

**Comment by niklasf** [comment]
meanwhile more mitigation for crashes has been added. and we fixed something that could have caused the crash we saw. let's make a new issue if we see new crashes
