### ISSUE TITLE
measure position complexity

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#58]

**Comment by apetresc** [comment]
What do you mean by that?

**Comment by ddugovic** [comment]
I'm assuming this doesn't mean [proof numbers](http://chessprogramming.wikispaces.com/Proof-number+search) since those only really apply to forced mates...

**Comment by niklasf** [comment]
This is related to ornicar/lila#275.

The challange will be to define what complexity is. I have only a vague idea. It should be so, that in complex positions humans are more likely to make mistakes. @ornicar Suggested to look at the engine eval as depth increases. Does it jump around a lot, even flap?

What can it be used for?
* User visible stats, for example in chess insights.
* As an additional parameter in cheating detection.
* Increase analysis time in complex positions.

**Comment by ddugovic** [comment]
LucasChess 8 defines a [complexity formula](http://www-lucaschess.rhcloud.com/static/pdf/english/advanced_info_%20in_LC8.pdf).

There's a separate idea of calculating complexity based on [PV move changes](http://github.com/ornicar/lila/issues/275#issuecomment-227026973).
