### ISSUE TITLE
RFC reduce user choices

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#64]
Users tend to make dubious choices. I see poorly configured fishnet nodes on my monitoring.

For instance someone using one core of 12 threads. Stockfish is not good at this, and the analysis have lower PV and depth.

I think fishnet should enforce 4 threads max, or maybe 6. And maybe totally remove that setting from the installation wizard, as I'm sure fishnet will make better choices on its own, generally. Then remove the cores setting as well.
They would stay available as settings, just not in the install wizard.

**Comment by ddugovic** [comment]
Maybe recommend values and/or impose tighter bounds during configuration

**Comment by ornicar** [comment]
Also I observed they get confused by the words `core` and `thread`. They thought they knew what that was but it means something else in fishnet.

**Comment by niklasf** [comment]
I removed those settings. Also `--threads` is now just a hint and fishnet will rather use more threads to avoid having a single instance with much less.
