### ISSUE TITLE
seen in logs after deploying sjeng

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#66]
https://gist.github.com/ornicar/7abfd81d1b8572bb1c3091de46f89946
https://gist.github.com/ornicar/89cb16af18db30a36732889613df62c0
https://gist.github.com/ornicar/e162d3534a0867ce6e15a9094f67a035
https://gist.github.com/ornicar/e211ffbf365340968ad07d989a71e142

**Comment by niklasf** [comment]
probably irrelevant now. i intend to give sunsetter another try soonish
