### ISSUE TITLE
crash on gandi

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#68]
fishnet stops working all of a sudden and fills the logs with this: https://gist.github.com/ornicar/7afccba73121f21eb498bc6f6694be40

A restart fixes it. It happened a few times already, usually after days (weeks?) or fishnet uptime.

Note that gandi is the IPv6 server. Hope it helps.

**Comment by niklasf** [comment]
seems like this was the ssh tunnel, not fishnet. reconfigured & successfully tested recovery after another proxy restart.
