### ISSUE TITLE
Analysis pauses when report is being sent to lichess server.

### ISSUE THREAD

**Issue by FYPetro** [niklasf/fishnet#73]
When I run fishnet, I found that each process would run for about 5 seconds and then attempt to send the results to server.  While fishnet attempts to contact the server to send the analysis, the process stops calculating.  Considering that my ping to lichess servers is relatively high, around 500ms or so, each fishnet process would calculate 5 positions and halt for about 1~2 seconds. 

If fishnet processes could continue to analyze while contacting the server, it would amount to a 20 to 40 percent increase in efficiency for me.

**Comment by niklasf** [comment]
Thanks for bringing this up. fishnet 1.14.0 will send progress reports in the background.

**Comment by FYPetro** [comment]
Follow-up: I sometimes get this warning.  Should I worry about anything?

`><> 4: WARNING: Could not keep up with progress reports. Dropping one.`

**Comment by niklasf** [comment]
It's not critical, but I'll see if you can avoid this in the next release.

**Comment by FYPetro** [comment]
To temporarily mitigate this situation, I set the `maxsize` to 20 because the queue gets clustered pretty quickly if it has a `maxsize` of 4.  Maybe fishnet should send all analysis in the queue via a single `POST`?

**Comment by FYPetro** [comment]
Possibly worthy of mentioning:

`if response.status != 204:`

Well, according to the protocol, both 204 and 202 mean that the analysis/move is accepted while 202 also gives a new job.

**Comment by niklasf** [comment]
The protocol could be more efficient for sure.

(Progress reports will never acquire a new job. That happens only when sending the final analysis result.)

**Comment by FYPetro** [comment]
I updated my fishnet; the queue `maxsize` is still 4.  It's really not enough, so I had to do something like:

`progress_reporter = ProgressReporter(max(len(buckets), 4) * 8, conf)`

**Comment by FYPetro** [comment]
Follow-up: I got these two messages today.

```
Thread-1: DEBUG: HTTP response: 202 Accepted
Thread-1: ERROR: Expected status 204 for progress report, got 202
```

**Comment by niklasf** [comment]
I played around with the queue size a bit (14bd247cce17640df0bfd28ba57a724614175a5b, it's still relatively small) and set the log level for dropped progress reports to debug. Skipping some reports is totally fine.

> Follow-up: I got these two messages today. [...]

That's wierd and indicates a bug somewhere. Please let me know if this occurs again or if you have some more context from the log.

**Comment by FYPetro** [comment]
It happened again.  I copied the logs from the command prompt to [gist](https://gist.github.com/FYPetro/3b968d9df535a7ff22b50e098cd87ae0#file-stockfish204-log).

**Comment by niklasf** [comment]
Thank you very much, this helped a lot. I was (naively) assuming Python's httplib is threadsafe. It is not, and the response belonged to a different request. Will fix ...

**Comment by ornicar** [comment]
> Or does later reports contain the analysis of all previous reports?

Yes, it does.
