### ISSUE TITLE
Provide way to do a "clean" shutdown

### ISSUE THREAD

**Issue by apetresc** [niklasf/fishnet#74]
At the moment, as far as I know, the only way to exit fishnet is to send it a SIGINT, usually with Ctrl-c. So if I don't want to cancel an analysis in progress, I have to watch and wait for the move counter to go to 0 and hope there isn't another one queued up.

It would be nice to have a signal handler for some other signal type that says "shut down after finishing all current analyses". Or even potentially make this the default behavior for SIGINT, and make it so that a *second* SIGINT force-quits.

**Comment by ddugovic** [comment]
For any process, I prefer that `SIGINT` interrupts execution (but that's my preference).

**Comment by FYPetro** [comment]
What if `SIGKILL` is used to interrupt the execution and exit fishnet immediately, `SIGINT` once for graceful exit, and `SIGINT` twice to achieve the same thing as `SIGKILL`?

**Comment by niklasf** [comment]
I like the  double-SIGINT idea. It's also not entirely uncommon.

fishnet also already handles SIGTERM to cleanly abort requests. So I would keep that in place. SIGKILL kills the process immediately and fishnet does not have a say in this.
