### ISSUE TITLE
Python 3: no module named 'requests'

### ISSUE THREAD

**Issue by FYPetro** [niklasf/fishnet#75]
I updated fishnet today and now I can't get it to run.  The script outputs the following and exits:

```
Traceback (most recent call last):
  File "fishnet.py", line 45, in <module>
    import requests
ImportError: No module named 'requests'
```

I first noticed this issue on `3.5.1`.  I updated to `3.6.1` and the issue persists.

**Comment by niklasf** [comment]
You can install the python-requests or python3-requests of your distro. (This is because the master branch is not yet officially released. Once it's published to pypy `pip install fishnet` will automatically install the dependency.)

**Comment by FYPetro** [comment]
Interesting!  Eventually I ran `pip install requests` and fishnet is up again.

**Comment by niklasf** [comment]
Nice. I'll keep this open as a reminder to document this for users who want to run from git.
