### ISSUE TITLE
Multiple exceptions raised: Engine process has died. Backing off...

### ISSUE THREAD

**Issue by FYPetro** [niklasf/fishnet#76]
I don't actually know what's going on, but here is the log.

https://gist.github.com/FYPetro/e5850475955ae9a9166afb02eabdbf63

**Comment by niklasf** [comment]
The error message is a bit misleading, I'll fix that. Lichess was just down a couple of seconds for a deploy.

**Comment by FYPetro** [comment]
Has the server been down sporadically for the past 8 hours?  I have been experiencing this issue for at least every ten minutes during this time frame.

**Comment by niklasf** [comment]
There were a couple more unscheduled deploys, but nothing on that order of magnitude. So something else is going on ...

**Comment by FYPetro** [comment]
Here is [a longer log](https://gist.github.com/FYPetro/337d65e98ebc397d8a09ce5e02b5a117).
