### ISSUE TITLE
write installation guide for non-technical users

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#79]
* [ ] Linux (maybe Ubuntu is most common for beginners?)
* [ ] Windows
* [ ] OS X

**Comment by niklasf** [comment]
Oh, thanks for letting me know. Which distro are you using?

The way it works for at least Debian, Ubuntu and Arch:
* `/etc/systemd/system` should be correct for manually managed services
* `/usr/lib/systemd/system` should be reserved for services installed from system packages
* `/lib/systemd/system` should be reserved for services installed from system packages that need to be available early on during boot (in case `/usr` is mounted later)

**Comment by frontfact** [comment]
I just tried again and all worked as intended.
sorry for the noise

**Comment by AlekseyLobanov** [comment]
Is it still actual? Can I write guide for linux-based systems?

**Comment by niklasf** [comment]
@AlekseyLobanov Absolutely :)

**Comment by fafamonge** [comment]
Somebody can tell me how to install on CentOS 7. I need help with this. I even don't know if Python is installed on the system.

**Comment by AlekseyLobanov** [comment]
I recommend you using virtualenv.
Follow https://www.vultr.com/docs/how-to-install-django-on-centos-7 until step4.
After that
```
virtualenv venv-fishnet
source venv-fishnet/bin/activate
pip install fishnet
```
And finally, you can run `python -m fishnet`
After restarting your system you just need to run
```
source venv-fishnet/bin/activate
python -m fishnet
```

All of these actions are safe for your system.

**Comment by fafamonge** [comment]
I followed this https://linuxize.com/post/how-to-install-python-3-on-centos-7/

Everything is okay, just awaiting for my 3 personal keys (I gonna install it in 3 different servers)

**Comment by niklasf** [comment]
video tutorial now linked in readme
