### ISSUE TITLE
Zombie Processes

### ISSUE THREAD

**Issue by mklemenz** [niklasf/fishnet#83]
I'm running fishnet within the docker container. Having 8 cores, it set up 2 stockfish workers, one with 3 threads, the other one with 4. After roughly 48 hours of running the container, 5 workers crashed resulting in as many zombie processes.
Recovery works, which means that a new 'replacement' worker is started automatically.
[workers.txt](https://github.com/niklasf/fishnet/files/1880883/workers.txt)
[logs.txt](https://github.com/niklasf/fishnet/files/1880885/logs.txt)

**Comment by niklasf** [comment]
Thanks for reporting. So there's two things to figure out: Why the segfaults, and why the zombies. I'll look into it soon.

**Comment by mklemenz** [comment]
glad to help. let me know if you need anything.

**Comment by mklemenz** [comment]
got some further testresults:
restarting the container produces 3 zombies immediately. I guess it might be connected with the '--auto-update' parameter. so appearently the update/process-stop-code might be involved somehow.

**Comment by niklasf** [comment]
Is that with or without the attempted fix 56990c9?

**Comment by mklemenz** [comment]
both. totally overlooked this commit before, but applied the changes manually right now.
it's the same result.

**Comment by niklasf** [comment]
Alright. At least we now have a way to reproduce the issue (I couldn't locally).

**Comment by niklasf** [comment]
Managed to reproduce it using Docker. It's actually the shell process wrapping Stockfish that are orphaned and not collected when running fishnet as pid 1. Fixed via 791881f5feb96837d7b5f979aa9b4a8a13c5c145.

**Comment by mklemenz** [comment]
works like a charm, thanks!
