### ISSUE TITLE
dockerhub update

### ISSUE THREAD

**Issue by mklemenz** [niklasf/fishnet#85]
so for the updated dockerfile from 791881f : could you reach out to @ageneau for providing the new container on hub.docker.com?

PS: if he's no longer available, I'd offer myself to take over maintainership for a new repo there.

**Comment by niklasf** [comment]
I am not too familiar with how this works. It would be cool if you could take care of it - I don't think ageneau will mind. Definitely feel free to submit a PR updating the maintainer field and anything else that's required.
