### ISSUE TITLE
Log files ?

### ISSUE THREAD

**Issue by lazydroid** [niklasf/fishnet#88]
I wonder if there are any log files, because I can see the fishnet is working (CPU load > 50%), but would like a bit more info, at least at the beginning, while I'm getting familiar with it?

**Comment by lazydroid** [comment]
Or maybe some stats might be useful, like "analyzed XXX positions today", etc... Or even a leaderboard, with aggregate stats for various users, their contribution size, things like that?

**Comment by niklasf** [comment]
Hi, thanks for helping to analyse games. How are you running fishnet?

If you are using `python -m fishnet` in a terminal it should show exactly which games it is analyzing and also regularly print some stats (like analyzed 39 positions, crunched 2940 million nodes).

If you're running using systemd there should be a journal (`journalctl -u fishnet` for the full log and `journalctl -fu fishnet` for a live view of the log).

**Comment by lazydroid** [comment]
I'm running fishnet as follows:

# Example usage:
# python -m fishnet systemd | sudo tee /etc/systemd/system/fishnet.service
# sudo systemctl enable fishnet.service
# sudo systemctl start fishnet.service

Thank you very much I'll check the journalctl output =)

**Comment by lazydroid** [comment]
> [fishnet v1.15.9] Analyzed 2323 positions, crunched 9006 million nodes

seems good so far =)
