### ISSUE TITLE
much slower than official stockfish

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#92]
@lakinwecker:
> I'm getting far less NPS on the fishnet stockfish than I am an official build. Like 1.6MN/s vs 2.6MN/s is this a known issue?

**Comment by lakinwecker** [comment]
https://gist.github.com/lakinwecker/7130508f7d227589b8f2c80c56aa24bc <- 4 threads
https://gist.github.com/lakinwecker/e13188b78efef6707efe6989d6646735 <- 1 thread

Latest stockfish downloaded from here: http://abrok.eu/stockfish/ I used the Linux x64 for modern computers link.   CPU is an AMD Threadripper 1950x

**Comment by lakinwecker** [comment]
I removed the version of the stockfish I have for fishnet as I was seeing a message that my copy was newer than the available one. It redownloaded a copy of stockfish. I have updated both gists with the new fishnet output.

**Comment by lakinwecker** [comment]
yeah. It's the difference between popcnt and haswell cpus on my computer. if I download the bmi2 one from the above link. The one under the "For Haswell CPUs", then I get comparable performance

**Comment by lakinwecker** [comment]
Yeah, from https://chessprogramming.wikispaces.com/BMI2 ```In 2017, BMI2 was further incorporated in AMD's Zen-architecture but so far with a slow implementation of critical instructions such as PDEP and PEXT [3] [4] .```

**Comment by niklasf** [comment]
Ah, good find! So it should be fixed by downloading the popcnt version, unless it's an Intel CPU.

**Comment by lakinwecker** [comment]
It works. My upgraded fishnet now runs the -modern version

**Comment by ddugovic** [comment]
Excellent!  I've updated my lichess-bot fork: https://github.com/ddugovic/lichess-bot/tree/download_github_release
