### ISSUE TITLE
See the quantity of analysis my server has done

### ISSUE THREAD

**Issue by fafamonge** [niklasf/fishnet#95]
I wonder know (see) the resume and detailed log about the analysis made by the server.

Something like:
"Your server has provided:
Up today 11,235 games analysis to 789 users
Today 434 games analysis to 101 users

Also,

This week...
Last hour..."

And maybe a way to see by variation, crazy and difficult stuff like this.

Where is stored this information? Thank you

**Comment by niklasf** [comment]
Thanks for helping us analyse games. We only have some of those stats, but I emailed you links to some semi-private dashboards.

**Comment by kehtabp** [comment]
@niklasf any chance I could get to see some of those dashboards, started donating last week and really curious how well my server is doing.
