### ISSUE TITLE
Fishnet and pypy3 with python 3.6

### ISSUE THREAD

**Issue by ysageev** [niklasf/fishnet#96]
Ahoy!

I'm trying optimize fishnet analysis, inspired by 
https://hackernoon.com/which-is-the-fastest-version-of-python-2ae7c61a6b2b

I successfully got fishnet to use pypy, but:

a) I can't get it to use pypy3
b) fishnet still wants to use python 2.7
c) does fishnet use C extensions or is it pure python?

so,

`pypy -m fishnet --auto-update`

works fine, but...

```
Engine target path: /home/XXXXX/stockfish-x86_64-modern
Looking up stockfish-x86_64-modern ...
Local stockfish-x86_64-modern is newer than release

### Checking configuration ...


Python: 2.7.13 (with requests 2.21.0)
EngineDir: /home/XXXXX
StockfishCommand: ./stockfish-x86_64-modern
Key: ********
Cores: 7
Engine processes: 2 (each ~3 threads)
Memory: 512 MB
Endpoint: lichess.org/fishnet/
FixedBackoff: False


### Starting workers ...
```
And
```
$ pypy3 -m fishnet --auto-update
/usr/bin/pypy3: No module named fishnet
```

**Comment by niklasf** [comment]
Fishnet works with pypy3. It just needs to be installed in a location where pypy3 can find it. For example:

```
pypy3 -m ensurepip
pypy3 -m pip install fishnet
pypy3 -m fishnet
```

Fishnet itself is pure Python (although it uses a trick to run some x86 machine code). But note that almost all time is spent running Stockfish, a chess engine written in C++. So swichting Python interpreters should barely have any impact.

**Comment by ysageev** [comment]
Ok thanks -- I won't monkey with it then, since no benefit.
